### ISSUE TITLE
Need some code refactor.

### ISSUE THREAD

**Issue by fxnoob** [short-d/short-ext#6]
![Screenshot 2019-08-26 at 9 30 31 AM](https://user-images.githubusercontent.com/24789277/63664507-6a377100-c7e4-11e9-90cc-d9c22e108bab.png)

So no need to copy some files on every build eg. package.json is almost static file. changes are very rare in that file. So placing `package.json` file in `extension` directory.  

merge build.sh into package.json scripts

**Comment by naturetime10** [comment]
As we discussed offline, the current build time is unnecessarily long during development.
I recommend keeping build.sh ( we can change its content instead. yarn is kept here for future continuous release on CI, where we don't have the NPM packages installed. The goal of build.sh is to generate final build for release ).

I recommend generating `.js file` and copy `manifest.json` into build directory so that we separate code and generated files. `yarn` and `zip generation` can be removed for development.

Please let me know if you disagree.

**Comment by fxnoob** [comment]
LGTM. made the changes.
